global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'producto-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8087'] #cambiar isto pelo IP local para parar o erro de não mostrar actuator
        labels:
          application: 'Producto Service Application'
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8089' ] # cambiar isto pelo IP local para parar o erro de não mostrar actuator
        labels:
          application: 'Order Service Application'
  - job_name: 'inventario-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8082' ] #cambiar isto pelo IP local para parar o erro de não mostrar actuator
        labels:
          application: 'Inventario Service Application'
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8086' ] #cambiar isto pelo IP local para parar o erro de não mostrar actuator
        labels:
          application: 'Notification Service Application'
  - job_name: 'message-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
     - targets: [ 'localhost:8091' ] #cambiar isto pelo IP local para parar o erro de não mostrar actuator
       labels:
       application: 'Message Service Application'